all:
	echo "nothing done for fpgautils, there are no source here"

clean:
	echo "nothing done for fpgautils, there are no source here"

install:
	echo "nothing done for fpgautils, there are no source here"
